#!/bin/bash
set -ex

# Copy figures to the right place
cp ../experiments/figure1/cls_xattr-vs-data.png figures/

# Build the paper
docker run --rm \
  --entrypoint=/bin/bash \
  -v `pwd`/:/mnt \
  ivotron/texlive:latest -c \
    "cd /mnt ; pdflatex paper && bibtex paper && pdflatex paper && pdflatex paper" &> build.log

if [ $? != "0" ] ; then
  echo "ERROR"
  cat build.log
  exit 1
fi

echo "SUCCESS"

exit 0
